### ISSUE TITLE
Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: net/schmizz/sshj/transport/verification/HostKeyVerifier

### ISSUE THREAD

**Issue by infinedi** [blueseerERP/blueseer#121]
I installed blueseer per the instructions.  It builds all right but when I try to run it, I get this error:  

ant -f C:\\Users\\art.didion\\Documents\\NetBeansProjects\\blueseer -Dnb.internal.action.name=run run
init:
Deleting: C:\Users\art.didion\Documents\NetBeansProjects\blueseer\build\built-jar.properties
deps-jar:
Updating property file: C:\Users\art.didion\Documents\NetBeansProjects\blueseer\build\built-jar.properties
compile:
run:
Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: net/schmizz/sshj/transport/verification/HostKeyVerifier
	at com.blueseer.utl.mf$1.run(mf.java:84)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.ClassNotFoundException: net.schmizz.sshj.transport.verification.HostKeyVerifier
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 14 more
BUILD SUCCESSFUL (total time: 1 second)
  

How do I get past this?

**Comment by vaughnte** [comment]
It appears to be missing a jar....you need to add sshj-0.32.0.jar.   In Netbeans....RIght click on 'Libraries' on the BlueSeer Project...then 'add JAR'....and add the above jar file.    The jar file can be found in the 'lib' source folder.

**Comment by infinedi** [comment]
You're an awesome programmer and I wanted to thank you for your quick reply.  I hope I can pay you back someday.

Thanks!

Arthur Didion
IT Representative
***@***.***

**Comment by infinedi** [comment]
When I build and run your code, the EDI menu is missing.  How do I include it in the build and running of the application.    That's the part I'm most interested in.

Arthur Didion
IT Representative
***@***.***
